<a href="https://colab.research.google.com/github/hansikachaudhary/-various-operations-on-an-array-through-a-simple-web-interface./blob/main/Copy_of_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY**
advantages:
*mathematical operations*,
*faster*




In [ ]:
import numpy as np


list vs numpy time taken


In [ ]:
from time import process_time
python_list=[i for i in range(10000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)


0.0004892700000009853


Time taken by a list

In [ ]:
python_list=[i for i in range(10000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)



0.0007272089999990072


In [ ]:
np_array=np.array([i for i in range(10000)])
start_time=process_time()
np_array+=5
end_time=process_time()
print(end_time-start_time)


0.0001525949999994225


Numpy arrays

In [ ]:
#list
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array=np.array([1,2,3,4])
print(np_array)
type(np_array)


[1 2 3 4]


numpy.ndarray

In [ ]:
#creating 1 D array
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

In [ ]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)
type(b)

[[1 2 3 4]
 [5 6 7 8]]


numpy.ndarray

In [ ]:
b.shape

(2, 4)

In [ ]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


INITIAL PLACEHOLDERS IN NUMPY ARRAY

In [ ]:
#create numpy array of zeroes
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#create a numpy array of ones
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#create a numpy array of a particular value
z=np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
#create an identity matrix
#return 2-D array with ones on the diagonal and zeros elsewhere
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#create a numpy array with random values
b=np.random.random((3,4))
print(b)

[[0.88957352 0.10688162 0.97410214 0.31683457]
 [0.96311405 0.03388521 0.92141145 0.01036241]
 [0.20428727 0.75616029 0.06895224 0.15369674]]


In [ ]:
b.shape

(3, 4)

In [ ]:
print(b.shape)

(3, 4)


In [ ]:
#no. of dimensions
print(b.ndim)

2


In [ ]:
#no. of elements in an array
print(b.size)


12


In [ ]:
print(b.dtype)

float64


In [ ]:
#random integer values array within a specific range
c=np.random.randint(10,100,(3,5))
print(c)

[[14 66 67 86 96]
 [61 97 58 25 32]
 [72 75 83 23 58]]


In [ ]:
#array of evenly spaced values --->specifying the number of values required
d=np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [ ]:
#array of evenly spaced values --->specifying the step
e=np.arange(10,30,5)
print (e)

[10 15 20 25]


In [ ]:
#convert list to array .....(list contins comas but array dont )
list2=[1,2,3,4]
np_array=np.asarray(list2)
print(np_array)
type(np_array)


[1 2 3 4]


numpy.ndarray

mathematical operations on numpy array

In [ ]:
c=np.random.randint(10,20,(4,4))
d=np.random.randint(20,30,(4,4))
print(c)
print(d)

[[19 12 19 17]
 [16 13 17 13]
 [15 11 15 14]
 [14 14 12 11]]
[[24 28 25 22]
 [21 28 26 23]
 [29 25 22 20]
 [24 24 29 28]]


In [ ]:
print(c+d)
print(c*d)
print(c-d)
print(c/d)
print(np.add(c,d))
print(np.subtract(c,d))
print(np.multiply(c,d))
print(np.divide(c,d))

[[43 40 44 39]
 [37 41 43 36]
 [44 36 37 34]
 [38 38 41 39]]
[[456 336 475 374]
 [336 364 442 299]
 [435 275 330 280]
 [336 336 348 308]]
[[ -5 -16  -6  -5]
 [ -5 -15  -9 -10]
 [-14 -14  -7  -6]
 [-10 -10 -17 -17]]
[[0.79166667 0.42857143 0.76       0.77272727]
 [0.76190476 0.46428571 0.65384615 0.56521739]
 [0.51724138 0.44       0.68181818 0.7       ]
 [0.58333333 0.58333333 0.4137931  0.39285714]]
[[43 40 44 39]
 [37 41 43 36]
 [44 36 37 34]
 [38 38 41 39]]
[[ -5 -16  -6  -5]
 [ -5 -15  -9 -10]
 [-14 -14  -7  -6]
 [-10 -10 -17 -17]]
[[456 336 475 374]
 [336 364 442 299]
 [435 275 330 280]
 [336 336 348 308]]
[[0.79166667 0.42857143 0.76       0.77272727]
 [0.76190476 0.46428571 0.65384615 0.56521739]
 [0.51724138 0.44       0.68181818 0.7       ]
 [0.58333333 0.58333333 0.4137931  0.39285714]]


Array Manipulation

In [ ]:
array =np.random.randint(10,20,(2,4))
print(array)
print(array.shape)

[[11 11 13 12]
 [14 17 15 11]]
(2, 4)


In [ ]:
#transpose(method 1)
trans=np.transpose(array)
print(trans)
print(trans.shape)

In [ ]:
array =np.random.randint(10,20,(2,4))
print(array)
print(array.shape)

[[18 19 19 17]
 [14 15 15 14]]
(2, 4)


In [ ]:
#transpose (method2)
trans2=array.T
print(trans2)
print(trans2.shape)


[[18 14]
 [19 15]
 [19 15]
 [17 14]]
(4, 2)
